"""Flow persistence in the workspace's flows/ directory."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from rayflow.schema.models import FlowDef, NodeDef
from rayflow.workspace import flows_path


def flow_to_dict(flow: FlowDef) -> dict[str, Any]:
    """Serializes a FlowDef into a JSON-serializable dict.

    Only writes user-facing fields (not the ones generated by flatten, like
    state_path, subflow_of, etc.). The `ui` field is preserved if present.
    """
    return {
        "name": flow.name,
        "version": flow.version,
        "outputs": flow.outputs,
        "variables": [
            {"name": v.name, "type": v.type, "default": v.default}
            for v in flow.variables
        ],
        "events": flow.events,
        "nodes": [_node_to_dict(n) for n in flow.nodes],
    }


def _node_to_dict(n: NodeDef) -> dict[str, Any]:
    d: dict[str, Any] = {"id": n.id, "type": n.type}
    if n.inputs:
        d["inputs"] = n.inputs
    if n.exec_in is not None:
        d["exec_in"] = n.exec_in
    if n.ui is not None:
        d["ui"] = n.ui
    return d


def _flow_path(name: str) -> Path:
    return flows_path() / f"{name}.json"


def list_flows() -> list[dict[str, Any]]:
    """Returns every flow in the flows/ directory as dicts."""
    base = flows_path()
    if not base.exists():
        return []
    result = []
    for p in sorted(base.glob("*.json")):
        try:
            result.append(json.loads(p.read_text(encoding="utf-8")))
        except Exception:
            pass
    return result


def get_flow_dict(name: str) -> dict[str, Any] | None:
    """Reads a flow by name. Returns None if it doesn't exist."""
    p = _flow_path(name)
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def save_flow(flow: FlowDef) -> None:
    """Saves a FlowDef to flows/{name}.json, creating the directory if needed."""
    base = flows_path()
    base.mkdir(parents=True, exist_ok=True)
    p = _flow_path(flow.name)
    p.write_text(json.dumps(flow_to_dict(flow), indent=2, ensure_ascii=False), encoding="utf-8")


def delete_flow(name: str) -> bool:
    """Deletes flows/{name}.json. Returns True if it existed."""
    p = _flow_path(name)
    if not p.exists():
        return False
    p.unlink()
    return True
