#!/usr/bin/env python3
"""Mechanically (re)generates rayflow_file_map.json from the real repo state:
file set via `git ls-files`, and depends_on/dependents edges for .py and
.ts/.tsx files computed by parsing real import statements with tree-sitter
(one Language/Parser pair per language, reused across files).

Wired at the pre-commit stage in .pre-commit-config.yaml (hook id
`file-map-generate`), first in the generator chain -- before `file-map-draft`
(scripts/draft_file_map_entries.py, which fills in real descriptions/systems
for files this script can only stub out), and well before
`claude-md-generate`/`agents-generate`/`sot-audit`, all of which read
rayflow_file_map.json downstream.

What this script does NOT do:
  - Does not touch `description` or `system` for a file this script has
    already seen before UNLESS that file is still an unverified draft (see
    below) -- those are curated prose/taxonomy, out of scope for a
    mechanical generator.
  - Does not invent new systems. A brand-new file gets the majority system
    among its directory siblings as a *candidate* (or the sentinel
    "UNASSIGNED" if there's no precedent), always still subject to
    confirmation by scripts/draft_file_map_entries.py's LLM pass.
  - Does not compute `systems.<name>.description` -- hand-authored, carried
    over verbatim from the file already on disk.

For a file with no map entry yet, this script writes a *draft* stub:
`description`/`system` get a cheap, no-LLM candidate value (marked
"[SIN VERIFICAR] ..." / possibly "UNASSIGNED" so no consumer ever sees a
bare None), plus a `_draft_candidate` object with the raw candidate data for
scripts/draft_file_map_entries.py to confirm-or-correct via a single batched
`rayflow-router` call. That key is removed once a file's draft is resolved;
while present, this script keeps refreshing the candidate every run instead
of freezing it at first sight (cheap, and file content may have changed).

Fails open per-file: a file that fails to parse just loses its edges for
this run (stderr warning), it doesn't abort the rest. Fails open overall
too if tree_sitter/its grammars aren't importable at all (recomputes with
depends_on/dependents = [] for every .py/.ts/.tsx file rather than
crashing) -- this script must never block a commit (always exits 0).

Usage: python3 scripts/generate_file_map.py
(no args; always operates on the whole repo from REPO_ROOT.)
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FILE_MAP_PATH = REPO_ROOT / "rayflow_file_map.json"

EXCLUDED_PREFIXES = ("rayflow/editor/static/dist/",)

SCHEMA_NOTE = (
    "Flat map of repo-relative file path -> {description, depends_on, "
    "dependents, system}. depends_on/dependents are computed from real "
    "imports for .py and .ts/.tsx files (via tree-sitter) -- other files "
    "have empty lists. A brand-new file gets a draft stub (description "
    "prefixed '[SIN VERIFICAR]', system possibly 'UNASSIGNED') until "
    "scripts/draft_file_map_entries.py's LLM pass confirms or corrects it "
    "(then the description is prefixed '[DRAFT sin revisar]' instead, and "
    "the temporary `_draft_candidate` key is removed). "
    "rayflow/editor/static/dist/ (compiled bundle) is intentionally "
    "excluded. Generated by scripts/generate_file_map.py (pre-commit hook "
    "`file-map-generate`); not wired into CLAUDE.md."
)
ROOT_DESCRIPTION = "rayflow — visual workflow orchestration on Ray"


# --------------------------------------------------------------------------
# tree-sitter setup (fails open: _TS_OK stays False if anything's missing)
# --------------------------------------------------------------------------
_TS_OK = True
try:
    import tree_sitter as _ts
    import tree_sitter_python as _tspy
    import tree_sitter_typescript as _tsts

    _PY_LANG = _ts.Language(_tspy.language())
    _TS_LANG = _ts.Language(_tsts.language_typescript())
    _TSX_LANG = _ts.Language(_tsts.language_tsx())

    _PY_PARSER = _ts.Parser(_PY_LANG)
    _TS_PARSER = _ts.Parser(_TS_LANG)
    _TSX_PARSER = _ts.Parser(_TSX_LANG)

    # Field names confirmed against a real installed tree-sitter-python
    # 0.25.0 (see scripts/generate_file_map.py history / task notes): `name`
    # on import_statement is either a bare `dotted_name` or an
    # `aliased_import` wrapping one; `module_name` on import_from_statement
    # is either a bare `dotted_name` (absolute) or a `relative_import` node
    # (whose children -- unnamed -- are an `import_prefix` token (the
    # literal dots) and an optional trailing `dotted_name`); `name` on
    # import_from_statement is the SAME field (repeated for `from x import
    # a, b`) and captures the imported names themselves (needed to detect
    # `from pkg import submodule`, where `submodule` may be a real tracked
    # file, not just a symbol inside `pkg/__init__.py`).
    #
    # We first capture whole `import_statement`/`import_from_statement`
    # nodes (`_PY_STATEMENT_QUERY`), then re-run the field-specific queries
    # below SCOPED to each individual statement node (QueryCursor.captures
    # accepts any node as the search root, not just the tree root) -- this
    # correlates a from-import's module with exactly its own imported
    # names even when a file has several from-imports, without depending on
    # `Node.children_by_field_name` (unconfirmed in this tree-sitter
    # version) or on `QueryCursor.matches()`'s exact return shape.
    _PY_STATEMENT_QUERY = _ts.QueryCursor(_ts.Query(
        _PY_LANG,
        "(import_statement) @stmt (import_from_statement) @stmt",
    ))
    _PY_ABS_IMPORT_NAME_QUERY = _ts.QueryCursor(_ts.Query(
        _PY_LANG,
        "(import_statement name: (dotted_name) @abs_name) "
        "(import_statement name: (aliased_import name: (dotted_name) @abs_name))",
    ))
    _PY_FROM_MODULE_QUERY = _ts.QueryCursor(_ts.Query(
        _PY_LANG,
        "(import_from_statement module_name: (dotted_name) @from_abs) "
        "(import_from_statement module_name: (relative_import) @from_rel)",
    ))
    _PY_FROM_NAME_QUERY = _ts.QueryCursor(_ts.Query(
        _PY_LANG,
        "(import_from_statement name: (dotted_name) @from_name) "
        "(import_from_statement name: (aliased_import name: (dotted_name) @from_name))",
    ))
    _PY_DOCSTRING_QUERY = _ts.QueryCursor(_ts.Query(
        _PY_LANG,
        "(module . (expression_statement (string) @doc))",
    ))

    def _ts_import_export_query(lang):
        # `source` is a field on both import_statement and export_statement
        # covering every form that carries a module specifier (default,
        # namespace, named, and bare re-exports like `export * from`).
        return _ts.QueryCursor(_ts.Query(
            lang,
            "(import_statement source: (string) @src) "
            "(export_statement source: (string) @src)",
        ))

    _TS_IMPORT_QUERY = _ts_import_export_query(_TS_LANG)
    _TSX_IMPORT_QUERY = _ts_import_export_query(_TSX_LANG)
except Exception as _exc:  # pragma: no cover - exercised only when deps missing
    _TS_OK = False
    sys.stderr.write(
        f"[file-map-generate] tree-sitter unavailable ({_exc!r}) -- "
        f"depends_on/dependents will be left empty for every .py/.ts/.tsx "
        f"file this run. Install `tree-sitter`, `tree-sitter-python`, "
        f"`tree-sitter-typescript` (see pyproject.toml [dev]) to fix.\n"
    )


def _read_bytes(path: Path) -> bytes | None:
    try:
        return path.read_bytes()
    except Exception:
        return None


def _text(node) -> str:
    return node.text.decode("utf-8", "replace")


# --------------------------------------------------------------------------
# Python: import extraction + resolution
# --------------------------------------------------------------------------
def _python_import_items(path: Path) -> list[dict]:
    """Returns one dict per import statement:
    {"module": <dotted name, dots already stripped>, "level": <int, 0 for
    absolute>, "names": [<imported name>, ...]} -- `names` is always [] for
    a plain `import a.b.c` (the whole dotted path IS the module, no
    ambiguity); for `from a.b import c, d` it's ["c", "d"], needed to tell
    apart "c is a real submodule file of a.b" from "c is just a symbol
    inside a/b/__init__.py"."""
    if not _TS_OK:
        return []
    src = _read_bytes(path)
    if src is None:
        return []
    try:
        tree = _PY_PARSER.parse(src)
        stmt_nodes = _PY_STATEMENT_QUERY.captures(tree.root_node).get("stmt", [])
    except Exception:
        return []

    items: list[dict] = []
    for stmt in stmt_nodes:
        try:
            if stmt.type == "import_statement":
                sub = _PY_ABS_IMPORT_NAME_QUERY.captures(stmt)
                for node in sub.get("abs_name", []):
                    items.append({"module": _text(node), "level": 0, "names": []})
            elif stmt.type == "import_from_statement":
                mod_captures = _PY_FROM_MODULE_QUERY.captures(stmt)
                level = 0
                module = None
                if mod_captures.get("from_abs"):
                    module = _text(mod_captures["from_abs"][0])
                elif mod_captures.get("from_rel"):
                    rel_node = mod_captures["from_rel"][0]
                    module = ""
                    for child in rel_node.children:
                        if child.type == "import_prefix":
                            level = len(_text(child))
                        elif child.type == "dotted_name":
                            module = _text(child)
                if module is None:
                    continue
                name_captures = _PY_FROM_NAME_QUERY.captures(stmt)
                names = [_text(n) for n in name_captures.get("from_name", [])]
                items.append({"module": module, "level": level, "names": names})
        except Exception:
            # One malformed statement shouldn't lose every other import in
            # an otherwise-parseable file.
            continue
    return items


_SYS_PATH_CALL_RE = re.compile(r"sys\.path\.(?:insert\(0,|append\()\s*str\((.*?)\)\)")
_QUOTED_SEGMENT_RE = re.compile(r'"([^"]+)"')
_FILE_DUNDER_RE = re.compile(r"^Path\(__file__\)\.resolve\(\)((?:\.parent)*)$")


def _extra_sys_path_dirs(file_src: str, importing_path: Path) -> list[Path]:
    """This repo's two real conventions for a bare, single-segment absolute
    import that only resolves via a runtime sys.path hack:
      (a) `sys.path.insert(0, str(Path(__file__).resolve().parent[...]))` --
          used by every .claude/hooks/*.py hook to import sibling helpers
          like `_file_map` -- resolved relative to the IMPORTING file's own
          directory (more `.parent`s walk further up).
      (b) `sys.path.insert(0, str(REPO_ROOT / "a" / "b"))` -- used by e.g.
          scripts/generate_specialist_agents.py to import `_sot_scope` from
          `.claude/hooks` -- resolved relative to the repo root.
    Best-effort text scan of the importing file's own source; not a real
    interpreter, just enough to recover this repo's two actual idioms."""
    dirs: list[Path] = []
    for line in file_src.splitlines():
        if "sys.path.insert" not in line and "sys.path.append" not in line:
            continue
        m = _SYS_PATH_CALL_RE.search(line)
        if not m:
            continue
        expr = m.group(1).strip()
        file_match = _FILE_DUNDER_RE.match(expr)
        if file_match:
            depth = file_match.group(1).count(".parent")
            d = importing_path.parent
            for _ in range(max(depth - 1, 0)):
                d = d.parent
            dirs.append(d)
            continue
        if expr.startswith("REPO_ROOT"):
            segments = _QUOTED_SEGMENT_RE.findall(expr)
            if segments:
                dirs.append(REPO_ROOT.joinpath(*segments))
    return dirs


def _rel_if_tracked(candidate: Path, tracked: set[str]) -> str | None:
    try:
        rel = candidate.resolve().relative_to(REPO_ROOT).as_posix()
    except (ValueError, OSError):
        return None
    return rel if rel in tracked else None


def _resolve_python_import_item(item: dict, importing_file: str, tracked: set[str]) -> set[str]:
    """Returns every tracked file this single import item depends on --
    usually one, but a `from pkg import sub1, sub2` where BOTH resolve to
    real submodule files yields two."""
    module, level, names = item["module"], item["level"], item["names"]
    edges: set[str] = set()
    importing_path = REPO_ROOT / importing_file

    parts = [p for p in module.split(".") if p]
    if level > 0:
        base_dir = importing_path.parent
        for _ in range(level - 1):
            base_dir = base_dir.parent
        candidate_dir = base_dir.joinpath(*parts) if parts else base_dir
    else:
        if not parts:
            return edges
        candidate_dir = REPO_ROOT.joinpath(*parts)

        # Bare, single-segment absolute module -- either `import x` or
        # `from x import a, b` -- that ISN'T a real top-level module/package
        # at the repo root: only resolvable, if at all, via this importing
        # file's own runtime sys.path hack (see _extra_sys_path_dirs), e.g.
        # `from _file_map import load_map, ...` in every .claude/hooks/*.py
        # hook (each inserts its own directory onto sys.path first) or
        # `import _sot_scope` in scripts/generate_specialist_agents.py
        # (inserts .claude/hooks). Gated on "doesn't already resolve at the
        # repo root" -- NOT on `names` being empty, since the from-import
        # form carries names too.
        if (
            len(parts) == 1
            and not _rel_if_tracked(candidate_dir.with_suffix(".py"), tracked)
            and not _rel_if_tracked(candidate_dir / "__init__.py", tracked)
        ):
            try:
                file_src = importing_path.read_text(encoding="utf-8")
            except Exception:
                file_src = ""
            for extra_dir in _extra_sys_path_dirs(file_src, importing_path):
                rel = _rel_if_tracked((extra_dir / parts[0]).with_suffix(".py"), tracked)
                if rel:
                    edges.add(rel)
            if edges:
                return edges

    module_as_file = _rel_if_tracked(candidate_dir.with_suffix(".py"), tracked)
    if module_as_file:
        # module_name resolved directly to a flat module file -- no
        # package/submodule ambiguity, `names` (if any) are just symbols
        # inside that same file.
        edges.add(module_as_file)
        return edges

    module_init = _rel_if_tracked(candidate_dir / "__init__.py", tracked)
    if not names:
        if module_init:
            edges.add(module_init)
        return edges

    # module_name resolved (or would resolve) to a PACKAGE directory --
    # each imported name might itself be a real submodule file (e.g.
    # `from rayflow.nodes.builtin import control` -> control.py), a more
    # precise edge than the package's own __init__.py.
    needs_init_fallback = False
    for name in names:
        sub_file = _rel_if_tracked((candidate_dir / name).with_suffix(".py"), tracked)
        sub_pkg = _rel_if_tracked(candidate_dir / name / "__init__.py", tracked)
        if sub_file:
            edges.add(sub_file)
        elif sub_pkg:
            edges.add(sub_pkg)
        else:
            needs_init_fallback = True

    if (needs_init_fallback or not edges) and module_init:
        edges.add(module_init)

    return edges


def _python_module_docstring(path: Path) -> str | None:
    if not _TS_OK:
        return None
    src = _read_bytes(path)
    if src is None:
        return None
    try:
        tree = _PY_PARSER.parse(src)
        captures = _PY_DOCSTRING_QUERY.captures(tree.root_node)
    except Exception:
        return None
    docs = captures.get("doc", [])
    if not docs:
        return None
    return _strip_python_string_literal(_text(docs[0]))


_STRING_PREFIX_RE = re.compile(r"^[rRbBuUfF]*")


def _strip_python_string_literal(text: str) -> str:
    text = text.strip()
    text = _STRING_PREFIX_RE.sub("", text, count=1)
    for quote in ('"""', "'''", '"', "'"):
        if text.startswith(quote) and text.endswith(quote) and len(text) >= 2 * len(quote):
            return text[len(quote):-len(quote)].strip()
    return text


# --------------------------------------------------------------------------
# TypeScript/TSX: import/export source extraction + resolution
# --------------------------------------------------------------------------
def _ts_capture_import_sources(path: Path) -> list[str]:
    if not _TS_OK:
        return []
    src = _read_bytes(path)
    if src is None:
        return []
    parser, query = (_TSX_PARSER, _TSX_IMPORT_QUERY) if path.suffix == ".tsx" else (_TS_PARSER, _TS_IMPORT_QUERY)
    try:
        tree = parser.parse(src)
        captures = query.captures(tree.root_node)
    except Exception:
        return []
    out = []
    for node in captures.get("src", []):
        frag = next((c for c in node.children if c.type == "string_fragment"), None)
        if frag is not None:
            out.append(_text(frag))
    return out


_TS_EXPORT_NAME_RE = re.compile(
    r"^export\s+(?:default\s+)?(?:async\s+)?(?:function\*?|class|const|let|interface|type)\s+(\w+)",
    re.MULTILINE,
)


def _ts_exported_symbol_names(path: Path) -> list[str]:
    """Deliberately crude: a plain regex over the raw source (not a
    tree-sitter query) is enough for a cheap, pre-LLM-verification "fact
    sheet" -- this is never presented as ground truth, only as a candidate
    for scripts/draft_file_map_entries.py to confirm or correct."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return []
    return _TS_EXPORT_NAME_RE.findall(text)[:15]


def _strip_jsonc_comments(text: str) -> str:
    """Strips `//` line comments and `/* */` block comments from JSONC
    text, tracking "are we inside a string literal" state character by
    character -- deliberately NOT a global regex (`//.*?$|/\\*.*?\\*/`),
    which cannot tell a real comment-opening `/*` apart from the exact same
    two characters occurring inside a JSON string value. This repo's own
    tsconfig.app.json has exactly that collision: the path alias is
    literally `"@/*": ["./src/*"]` -- a naive regex reads that `/*` as the
    start of a block comment and eats the rest of the file up to the next
    real `*/`, silently emptying every alias this generator needs to
    resolve `@/...` imports."""
    out: list[str] = []
    i = 0
    n = len(text)
    in_string = False
    while i < n:
        ch = text[i]
        if in_string:
            out.append(ch)
            if ch == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if ch == '"':
                in_string = False
            i += 1
            continue
        if ch == '"':
            in_string = True
            out.append(ch)
            i += 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            nl = text.find("\n", i)
            i = n if nl == -1 else nl
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "*":
            end = text.find("*/", i + 2)
            i = n if end == -1 else end + 2
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def _load_ts_alias_configs(tracked: set[str]) -> list[tuple[Path, str, Path]]:
    """Returns (config_dir, alias_prefix, target_dir) tuples -- e.g.
    (.../rayflow/editor/frontend, '@/', .../rayflow/editor/frontend/src) for
    every tsconfig*.json in the repo that declares a `paths` alias, so `@/x`
    resolves under THAT config's own directory rather than a hardcoded
    repo-wide assumption. Sorted deepest-directory-first so the most
    specific applicable config wins when more than one could match."""
    configs = []
    for rel in tracked:
        name = Path(rel).name
        if not (name.startswith("tsconfig") and name.endswith(".json")):
            continue
        abs_path = REPO_ROOT / rel
        try:
            data = json.loads(_strip_jsonc_comments(abs_path.read_text(encoding="utf-8")))
        except Exception:
            continue
        opts = data.get("compilerOptions", {}) if isinstance(data, dict) else {}
        paths = opts.get("paths", {}) or {}
        base_url = opts.get("baseUrl", ".")
        config_dir = abs_path.parent
        for alias_pattern, targets in paths.items():
            if not targets or "*" not in alias_pattern:
                continue
            alias_prefix = alias_pattern.split("*")[0]
            target_prefix = targets[0].split("*")[0]
            target_dir = (config_dir / base_url / target_prefix).resolve()
            configs.append((config_dir.resolve(), alias_prefix, target_dir))
    configs.sort(key=lambda c: len(str(c[0])), reverse=True)
    return configs


_TS_RESOLVE_SUFFIXES = (".tsx", ".ts", ".jsx", ".js")


def _resolve_ts_specifier(specifier: str, importing_file: str, tracked: set[str], alias_configs) -> str | None:
    importing_path = REPO_ROOT / importing_file
    base: Path | None = None
    if specifier.startswith("."):
        base = (importing_path.parent / specifier).resolve()
    else:
        for config_dir, alias_prefix, target_dir in alias_configs:
            if importing_path.resolve().is_relative_to(config_dir) and specifier.startswith(alias_prefix):
                base = (target_dir / specifier[len(alias_prefix):]).resolve()
                break
        if base is None:
            return None  # bare package specifier (node_modules) -- not ours to resolve

    candidates = [base]
    for suf in _TS_RESOLVE_SUFFIXES:
        candidates.append(Path(str(base) + suf))
        candidates.append(base / f"index{suf}")
    for candidate in candidates:
        try:
            rel = candidate.resolve().relative_to(REPO_ROOT).as_posix()
        except (ValueError, OSError):
            continue
        if rel in tracked:
            return rel
    return None


# --------------------------------------------------------------------------
# Directory-sibling heuristics for brand-new files (no LLM)
# --------------------------------------------------------------------------
def _directory_of(rel_path: str) -> str:
    parent = str(Path(rel_path).parent)
    return "" if parent == "." else parent.replace("\\", "/")


def _sibling_system_candidate(rel_path: str, files: dict) -> tuple[str | None, str]:
    directory = _directory_of(rel_path)
    siblings_systems = [
        info.get("system")
        for p, info in files.items()
        if p != rel_path and _directory_of(p) == directory
        and info.get("system") and info.get("system") != "UNASSIGNED"
    ]
    if not siblings_systems:
        return None, "no_precedent"
    counts = Counter(siblings_systems)
    top_system, _top_count = counts.most_common(1)[0]
    confidence = "unanimous" if len(counts) == 1 else "split"
    return top_system, confidence


def _neighbor_description_bits(rel_path: str, files: dict) -> str:
    directory = _directory_of(rel_path)
    bits = []
    for p, info in sorted(files.items()):
        if p == rel_path or _directory_of(p) != directory:
            continue
        desc = (info.get("description") or "").split(".")[0]
        if desc:
            bits.append(f"{Path(p).name}: {desc}.")
        if len(bits) >= 4:
            break
    if not bits:
        return "Sin otros archivos en el mismo directorio para comparar."
    return "Vecinos del mismo directorio -- " + " ".join(bits)


def _description_candidate(rel_path: str, files: dict) -> str:
    abs_path = REPO_ROOT / rel_path
    if rel_path.endswith(".py"):
        doc = _python_module_docstring(abs_path)
        if doc:
            return doc[:600]
    if rel_path.endswith((".ts", ".tsx")):
        symbols = _ts_exported_symbol_names(abs_path)
        if symbols:
            return (
                f"Archivo nuevo ({Path(rel_path).name}). Simbolos exportados detectados: "
                f"{', '.join(symbols)}. {_neighbor_description_bits(rel_path, files)}"
            ).strip()
    return f"Archivo nuevo ({Path(rel_path).name}), sin docstring de modulo. {_neighbor_description_bits(rel_path, files)}".strip()


# --------------------------------------------------------------------------
# Main assembly
# --------------------------------------------------------------------------
def _git_ls_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return [line.strip() for line in out.splitlines() if line.strip()]


def _load_old_map() -> dict:
    try:
        return json.loads(FILE_MAP_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _compute_edges(rel_path: str, tracked: set[str], alias_configs) -> list[str]:
    abs_path = REPO_ROOT / rel_path
    try:
        if rel_path.endswith(".py"):
            edges = set()
            for item in _python_import_items(abs_path):
                edges |= _resolve_python_import_item(item, rel_path, tracked)
            edges.discard(rel_path)
            return sorted(edges)
        if rel_path.endswith((".ts", ".tsx")):
            edges = set()
            for spec in _ts_capture_import_sources(abs_path):
                resolved = _resolve_ts_specifier(spec, rel_path, tracked, alias_configs)
                if resolved and resolved != rel_path:
                    edges.add(resolved)
            return sorted(edges)
    except Exception as exc:
        sys.stderr.write(f"[file-map-generate] failed to compute edges for {rel_path}: {exc!r}\n")
        return []
    return []


def build_files(tracked: list[str], old_files: dict) -> dict:
    tracked_set = set(tracked)
    alias_configs = _load_ts_alias_configs(tracked_set) if _TS_OK else []

    files: dict = {}
    for rel_path in tracked:
        old_entry = old_files.get(rel_path)
        depends_on = _compute_edges(rel_path, tracked_set, alias_configs)

        if old_entry is not None and "_draft_candidate" not in old_entry:
            files[rel_path] = {
                "description": old_entry.get("description", ""),
                "depends_on": depends_on,
                "dependents": [],
                "system": old_entry.get("system"),
            }
            continue

        system_candidate, confidence = _sibling_system_candidate(rel_path, old_files)
        desc_candidate = _description_candidate(rel_path, old_files)
        files[rel_path] = {
            "description": f"[SIN VERIFICAR] {desc_candidate}",
            "depends_on": depends_on,
            "dependents": [],
            "system": system_candidate or "UNASSIGNED",
            "_draft_candidate": {
                "description": desc_candidate,
                "system": system_candidate,
                "system_confidence": confidence,
            },
        }

    for rel_path, entry in files.items():
        for dep in entry["depends_on"]:
            if dep in files:
                files[dep]["dependents"].append(rel_path)
    for entry in files.values():
        entry["dependents"] = sorted(set(entry["dependents"]))

    return files


def build_systems(files: dict, old_systems: dict) -> dict:
    systems: dict = {}
    by_system: dict[str, list[str]] = {}
    for rel_path, entry in files.items():
        sysname = entry.get("system")
        if not sysname or sysname == "UNASSIGNED":
            continue
        by_system.setdefault(sysname, []).append(rel_path)

    for sysname, rel_paths in by_system.items():
        old_info = old_systems.get(sysname, {})
        depends_on_systems = set()
        dependents_systems = set()
        for rel_path in rel_paths:
            for dep in files[rel_path]["depends_on"]:
                dep_sys = files.get(dep, {}).get("system")
                if dep_sys and dep_sys != sysname and dep_sys != "UNASSIGNED":
                    depends_on_systems.add(dep_sys)
            for dependent in files[rel_path]["dependents"]:
                dep_sys = files.get(dependent, {}).get("system")
                if dep_sys and dep_sys != sysname and dep_sys != "UNASSIGNED":
                    dependents_systems.add(dep_sys)
        systems[sysname] = {
            "description": old_info.get("description", ""),
            "macrosistemas": old_info.get("macrosistemas", []),
            "files": sorted(rel_paths),
            "depends_on_systems": sorted(depends_on_systems),
            "dependents_systems": sorted(dependents_systems),
        }
    return systems


def main() -> int:
    try:
        tracked = [p for p in _git_ls_files() if not p.startswith(EXCLUDED_PREFIXES)]
    except Exception as exc:
        sys.stderr.write(f"[file-map-generate] `git ls-files` failed ({exc!r}) -- not touching the file map.\n")
        return 0

    old_map = _load_old_map()
    old_files = old_map.get("files", {})
    old_systems = old_map.get("systems", {})

    files = build_files(tracked, old_files)
    systems = build_systems(files, old_systems)

    new_map = {
        "$schema_note": SCHEMA_NOTE,
        "root": old_map.get("root", ROOT_DESCRIPTION),
        "file_count": len(files),
        "files": {k: files[k] for k in sorted(files)},
        "systems": {k: systems[k] for k in sorted(systems)},
    }

    new_content = json.dumps(new_map, indent=2, ensure_ascii=False) + "\n"
    old_content = FILE_MAP_PATH.read_text(encoding="utf-8") if FILE_MAP_PATH.exists() else None
    if new_content == old_content:
        return 0

    FILE_MAP_PATH.write_text(new_content, encoding="utf-8")
    subprocess.run(["git", "add", str(FILE_MAP_PATH)], cwd=REPO_ROOT, check=False)

    new_stubs = [p for p, e in files.items() if "_draft_candidate" in e]
    sys.stderr.write(
        f"[file-map-generate] Regenerated and staged {FILE_MAP_PATH.name} "
        f"({len(files)} files, {len(new_stubs)} unverified draft(s)"
        + (f": {', '.join(new_stubs[:10])}{'...' if len(new_stubs) > 10 else ''}" if new_stubs else "")
        + ").\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
